from __future__ import annotations

import struct
import zlib
from pathlib import Path

from printstash_core.gcode import (
    GcodeMetadata,
    MaterialRequirement,
    bgcode,
    is_valid_container,
    parse,
)

_FILE_METADATA = 0
_GCODE = 1
_THUMBNAIL = 5


def _block(
    block_type: int,
    params: bytes,
    data: bytes,
    *,
    compression: int,
) -> bytes:
    body = zlib.compress(data) if compression == 1 else data
    header = struct.pack("<HHI", block_type, compression, len(data))
    if compression != 0:
        header += struct.pack("<I", len(body))
    return header + params + body


def _container(*blocks: bytes) -> bytes:
    return b"GCDE" + struct.pack("<IH", 1, 0) + b"".join(blocks)


def _sample_container() -> bytes:
    metadata = _block(
        _FILE_METADATA,
        struct.pack("<H", 0),
        b"Producer=PrusaSlicer 2.8.0\nfilament_type=PETG\n",
        compression=1,
    )
    thumbnail = _block(
        _THUMBNAIL,
        struct.pack("<HHH", 0, 16, 16),
        b"thumbnail-bytes",
        compression=1,
    )
    gcode = _block(
        _GCODE,
        struct.pack("<H", 2),
        b"opaque-heatshrink",
        compression=3,
    )
    return _container(metadata, thumbnail, gcode)


def test_valid_container_and_typed_metadata(tmp_path: Path) -> None:
    path = tmp_path / "sample.bgcode"
    path.write_bytes(_sample_container())

    assert is_valid_container(path) is True
    assert parse(path) == GcodeMetadata(
        slicer_name="PrusaSlicer",
        slicer_version="PrusaSlicer 2.8.0",
        material_type="PETG",
        material_requirements=(MaterialRequirement(0, "PETG"),),
    )
    assert list(bgcode.iter_thumbnails(path)) == [(0, 16, 16, b"thumbnail-bytes")]


def test_container_validation_rejects_truncation_and_bad_deflate(
    tmp_path: Path,
) -> None:
    truncated = tmp_path / "truncated.bgcode"
    truncated.write_bytes(_sample_container()[:40])
    assert is_valid_container(truncated) is False

    corrupt_metadata = (
        struct.pack("<HHI", _FILE_METADATA, 1, 1000)
        + struct.pack("<I", len(b"not-deflate"))
        + struct.pack("<H", 0)
        + b"not-deflate"
    )
    gcode = _block(
        _GCODE,
        struct.pack("<H", 2),
        b"opaque",
        compression=3,
    )
    corrupt = tmp_path / "corrupt.bgcode"
    corrupt.write_bytes(_container(corrupt_metadata, gcode))
    assert is_valid_container(corrupt) is False


def test_bounded_decompress_rejects_oversize_partial_and_trailing_streams() -> None:
    compressed = zlib.compress(b"x" * 8192)
    assert bgcode._decompress(1, compressed, max_output=1024) is None

    valid = zlib.compress(b"metadata")
    assert bgcode._decompress(1, valid[:-1], max_output=1024) is None
    assert bgcode._decompress(1, valid + b"trailing", max_output=1024) is None


def test_container_requires_a_printable_gcode_block(tmp_path: Path) -> None:
    metadata_only = tmp_path / "metadata-only.bgcode"
    metadata_only.write_bytes(
        _container(
            _block(
                _FILE_METADATA,
                struct.pack("<H", 0),
                b"Producer=PrusaSlicer 2.8.0\n",
                compression=0,
            )
        )
    )

    assert is_valid_container(metadata_only) is False


def test_container_validation_skips_large_printable_body(tmp_path: Path) -> None:
    """Printable blocks are seeked, not read, so their size is not metadata-capped."""
    path = tmp_path / "large-sparse.bgcode"
    body_size = bgcode._MAX_BLOCK_DATA + 1
    with path.open("wb") as file:
        file.write(b"GCDE" + struct.pack("<IH", 1, 0))
        file.write(struct.pack("<HHI", _GCODE, 0, body_size))
        file.write(struct.pack("<H", 2))
        file.seek(body_size - 1, 1)
        file.write(b"\0")

    assert is_valid_container(path) is True


class TestIsBgcode:
    def test_recognises_the_container_magic(self, tmp_path: Path) -> None:
        path = tmp_path / "sample.bgcode"
        path.write_bytes(_sample_container())

        assert bgcode.is_bgcode(path) is True

    def test_rejects_a_file_that_is_not_binary_gcode(self, tmp_path: Path) -> None:
        path = tmp_path / "plain.gcode"
        path.write_bytes(b"; generated by PrusaSlicer\nG28\n")

        # The magic is the only cheap way to tell the two formats apart before
        # committing to a parse, and a plain G-code file must take the text path.
        assert bgcode.is_bgcode(path) is False

    def test_rejects_a_file_shorter_than_the_magic(self, tmp_path: Path) -> None:
        path = tmp_path / "tiny.bgcode"
        path.write_bytes(b"GC")

        assert bgcode.is_bgcode(path) is False

    def test_reports_an_unreadable_file_as_not_bgcode(self, tmp_path: Path) -> None:
        # A directory is the portable way to make `open` raise OSError. An
        # unreadable file is not a bgcode file, and it must not propagate.
        assert bgcode.is_bgcode(tmp_path) is False


class TestIsValidContainerFraming:
    """Every framing field is attacker-controlled, so each gets its own refusal."""

    def test_rejects_a_wrong_magic(self, tmp_path: Path) -> None:
        path = tmp_path / "bad.bgcode"
        path.write_bytes(b"NOPE" + struct.pack("<IH", 1, 0))

        assert is_valid_container(path) is False

    def test_rejects_a_header_shorter_than_ten_bytes(self, tmp_path: Path) -> None:
        path = tmp_path / "short.bgcode"
        path.write_bytes(b"GCDE" + struct.pack("<I", 1))

        # The header carries a version and a checksum type; a truncated one means
        # the checksum length is unknown and every subsequent offset is a guess.
        assert is_valid_container(path) is False

    def test_rejects_a_container_with_no_blocks(self, tmp_path: Path) -> None:
        path = tmp_path / "empty.bgcode"
        path.write_bytes(_container())

        assert is_valid_container(path) is False

    def test_rejects_a_block_header_cut_short(self, tmp_path: Path) -> None:
        path = tmp_path / "cut.bgcode"
        path.write_bytes(_container(struct.pack("<HH", _GCODE, 0)))

        assert is_valid_container(path) is False

    def test_rejects_a_missing_compressed_size(self, tmp_path: Path) -> None:
        path = tmp_path / "nosize.bgcode"
        # Declares deflate, so a 4-byte compressed size must follow the header.
        path.write_bytes(_container(struct.pack("<HHI", _GCODE, 1, 10)))

        assert is_valid_container(path) is False

    def test_rejects_params_cut_short(self, tmp_path: Path) -> None:
        path = tmp_path / "noparams.bgcode"
        # A G-code block declares two parameter bytes; supply one.
        path.write_bytes(_container(struct.pack("<HHI", _GCODE, 0, 0) + b"\x00"))

        assert is_valid_container(path) is False

    def test_rejects_a_block_that_declares_more_data_than_the_file_holds(
        self, tmp_path: Path
    ) -> None:
        path = tmp_path / "overrun.bgcode"
        header = struct.pack("<HHI", _GCODE, 0, 1_000_000) + struct.pack("<H", 0)
        path.write_bytes(_container(header + b"short"))

        # The declared size is checked against the real file size *before* any
        # read, so a hostile length cannot make the parser allocate for it.
        assert is_valid_container(path) is False

    def test_rejects_an_unknown_compression_scheme(self, tmp_path: Path) -> None:
        path = tmp_path / "weird.bgcode"
        metadata = _block(
            _FILE_METADATA, struct.pack("<H", 0), b"Producer=X\n", compression=1
        )
        # Compression 7 does not exist. The scheme is an allowlist rather than a
        # blocklist, so an unknown value is refused rather than passed through.
        weird = struct.pack("<HHI", _FILE_METADATA, 7, 4) + struct.pack("<I", 4)
        weird += struct.pack("<H", 0) + b"data"
        gcode = _block(_GCODE, struct.pack("<H", 2), b"body", compression=0)
        path.write_bytes(_container(metadata, weird, gcode))

        assert is_valid_container(path) is False

    def test_rejects_a_decoded_size_that_disagrees_with_the_header(
        self, tmp_path: Path
    ) -> None:
        path = tmp_path / "lying.bgcode"
        body = zlib.compress(b"Producer=X\n")
        # Claim 9999 uncompressed bytes while the stream holds far fewer.
        header = struct.pack("<HHI", _FILE_METADATA, 1, 9999)
        header += struct.pack("<I", len(body)) + struct.pack("<H", 0)
        gcode = _block(_GCODE, struct.pack("<H", 2), b"body", compression=0)
        path.write_bytes(_container(header + body, gcode))

        # A header that disagrees with its own payload is the shape of a
        # decompression bomb, so the two are compared after decoding.
        assert is_valid_container(path) is False

    def test_skips_a_checksum_between_blocks(self, tmp_path: Path) -> None:
        path = tmp_path / "crc.bgcode"
        metadata = (
            _block(
                _FILE_METADATA,
                struct.pack("<H", 0),
                b"Producer=PrusaSlicer 2.8.0\n",
                compression=1,
            )
            + b"\x00\x00\x00\x00"
        )
        gcode = _block(_GCODE, struct.pack("<H", 2), b"body", compression=0)
        gcode += b"\x00\x00\x00\x00"
        # checksum_type 1 means every block carries a trailing CRC32.
        path.write_bytes(b"GCDE" + struct.pack("<IH", 1, 1) + metadata + gcode)

        # A parser that ignored the checksum length would read it as the next
        # block header and reject a perfectly valid file.
        assert is_valid_container(path) is True

    def test_reports_an_unreadable_path_as_invalid(self, tmp_path: Path) -> None:
        assert is_valid_container(tmp_path / "missing.bgcode") is False


class TestReadMetadataText:
    def test_returns_the_decoded_metadata_block(self, tmp_path: Path) -> None:
        path = tmp_path / "sample.bgcode"
        path.write_bytes(_sample_container())

        text = bgcode.read_metadata_text(path)

        assert text is not None
        assert "Producer=PrusaSlicer 2.8.0" in text

    def test_returns_nothing_for_a_file_that_is_not_bgcode(
        self, tmp_path: Path
    ) -> None:
        path = tmp_path / "plain.gcode"
        path.write_bytes(b"G28\n")

        assert bgcode.read_metadata_text(path) is None

    def test_returns_nothing_for_a_missing_file(self, tmp_path: Path) -> None:
        # A queued parse races the library: the artifact can be purged between
        # the job being enqueued and the parse starting.
        assert bgcode.read_metadata_text(tmp_path / "gone.bgcode") is None

    def test_returns_nothing_when_the_metadata_block_is_absent(
        self, tmp_path: Path
    ) -> None:
        path = tmp_path / "gcode-only.bgcode"
        path.write_bytes(
            _container(_block(_GCODE, struct.pack("<H", 2), b"body", compression=0))
        )

        # A container with a printable body and no metadata is valid; there is
        # simply nothing to report, which is different from a parse failure.
        assert bgcode.read_metadata_text(path) is None

    def test_stops_at_a_truncated_block_without_raising(self, tmp_path: Path) -> None:
        path = tmp_path / "truncated.bgcode"
        path.write_bytes(_container(struct.pack("<HH", _FILE_METADATA, 0)))

        # A partially written file is common — a slicer interrupted mid-export —
        # and it must read as "no metadata" rather than crash the ingest job.
        assert bgcode.read_metadata_text(path) is None


class TestIterThumbnails:
    def test_yields_the_embedded_preview_with_its_dimensions(
        self, tmp_path: Path
    ) -> None:
        path = tmp_path / "sample.bgcode"
        path.write_bytes(_sample_container())

        thumbnails = list(bgcode.iter_thumbnails(path))

        assert [(width, height) for _fmt, width, height, _data in thumbnails] == [
            (16, 16)
        ]

    def test_yields_nothing_for_a_container_without_one(self, tmp_path: Path) -> None:
        path = tmp_path / "no-thumb.bgcode"
        path.write_bytes(
            _container(_block(_GCODE, struct.pack("<H", 2), b"body", compression=0))
        )

        assert list(bgcode.iter_thumbnails(path)) == []

    def test_yields_nothing_for_a_missing_file(self, tmp_path: Path) -> None:
        assert list(bgcode.iter_thumbnails(tmp_path / "gone.bgcode")) == []

    def test_yields_nothing_for_a_file_that_is_not_bgcode(self, tmp_path: Path) -> None:
        path = tmp_path / "plain.gcode"
        path.write_bytes(b"G28\n")

        assert list(bgcode.iter_thumbnails(path)) == []
