"""Tests for G-code revision metadata on model files."""

from __future__ import annotations

from pathlib import Path

import pytest
from fastapi.testclient import TestClient
from sqlmodel import Session

from app.core.config import _overlay
from app.db.models import (
    Collection,
    CollectionPermission,
    CollectionRole,
    File,
    FileType,
    Model,
    User,
)
from app.services.auth import create_access_token, hash_password


def _model(db_session: Session, *, slug: str = "bracket") -> Model:
    model = Model(name="Bracket", slug=slug, hash=f"{slug:0<64}"[:64])
    db_session.add(model)
    db_session.commit()
    db_session.refresh(model)
    return model


def _file(
    db_session: Session,
    model: Model,
    *,
    file_type: FileType = FileType.GCODE,
    version: int = 1,
    sha: str = "a",
) -> File:
    file_row = File(
        model_id=model.id,
        path=f"/data/files/{model.slug}/v{version}/file-{version}.gcode",
        original_filename=f"file-{version}.gcode",
        file_type=file_type,
        version=version,
        size_bytes=123,
        sha256=sha * 64,
    )
    db_session.add(file_row)
    db_session.commit()
    db_session.refresh(file_row)
    return file_row


def _configure_storage(tmp_path: Path) -> None:
    _overlay["data_dir"] = tmp_path / "files"
    _overlay["thumb_dir"] = tmp_path / "thumbs"
    _overlay["staging_dir"] = tmp_path / "staging"


def _large_gcode(min_bytes: int = 1_200_000) -> bytes:
    payload = b"; generated by OrcaSlicer\nG90\nG1 X1 Y1 E1\n"
    payload += b"; padding to exceed nginx default body limit\n" * (min_bytes // 45)
    return payload


def _regular_user(session: Session, username: str = "regular") -> User:
    user = User(
        username=username,
        hashed_password=hash_password("Password123"),
        is_active=True,
        is_superuser=False,
    )
    session.add(user)
    session.commit()
    session.refresh(user)
    return user


def _headers_for(user: User) -> dict[str, str]:
    scope = "admin" if user.is_superuser else "write"
    token = create_access_token(user.id, user.username, scope=scope)
    return {"Authorization": f"Bearer {token}"}


def test_star_and_unstar_model(
    client: TestClient, auth_headers: dict[str, str], db_session: Session
) -> None:
    model = _model(db_session)
    starred = client.put(f"/api/v1/models/{model.id}/star", headers=auth_headers)
    assert starred.status_code == 200
    assert starred.json() == {"model_id": model.id, "starred": True}
    # Idempotent — starring twice does not error or duplicate the row.
    again = client.put(f"/api/v1/models/{model.id}/star", headers=auth_headers)
    assert again.status_code == 200

    unstarred = client.delete(f"/api/v1/models/{model.id}/star", headers=auth_headers)
    assert unstarred.status_code == 200
    assert unstarred.json() == {"model_id": model.id, "starred": False}


# --------------------------------------------------------------------------- #
# Batch operations.
# --------------------------------------------------------------------------- #
def test_batch_move_models_to_new_collection(
    client: TestClient, auth_headers: dict[str, str], db_session: Session
) -> None:
    a = _model(db_session, slug="batch-a")
    b = _model(db_session, slug="batch-b")

    resp = client.post(
        "/api/v1/models/batch/move",
        json={"model_ids": [a.id, b.id], "collection": "new/spot"},
        headers=auth_headers,
    )
    assert resp.status_code == 200
    body = resp.json()
    assert set(body["succeeded_ids"]) == {a.id, b.id}
    assert body["failed_count"] == 0


def test_batch_move_models_root_requires_superuser(
    client: TestClient, db_session: Session
) -> None:
    user = _regular_user(db_session)
    model = _model(db_session)
    resp = client.post(
        "/api/v1/models/batch/move",
        json={"model_ids": [model.id], "collection": ""},
        headers=_headers_for(user),
    )
    assert resp.status_code == 403
    assert resp.json()["detail"] == "root_collection_admin_required"


def test_batch_move_models_reports_missing_model(
    client: TestClient, auth_headers: dict[str, str]
) -> None:
    resp = client.post(
        "/api/v1/models/batch/move",
        json={"model_ids": [999999], "collection": "somewhere"},
        headers=auth_headers,
    )
    assert resp.status_code == 404


def test_batch_tag_models_adds_and_removes(
    client: TestClient, auth_headers: dict[str, str], db_session: Session
) -> None:
    a = _model(db_session, slug="tag-a")
    b = _model(db_session, slug="tag-b")

    added = client.post(
        "/api/v1/models/batch/tags",
        json={"model_ids": [a.id, b.id], "add": ["shiny"], "remove": []},
        headers=auth_headers,
    )
    assert added.status_code == 200
    assert added.json()["succeeded_count"] == 2

    removed = client.post(
        "/api/v1/models/batch/tags",
        json={"model_ids": [a.id], "add": [], "remove": ["shiny"]},
        headers=auth_headers,
    )
    assert removed.status_code == 200
    detail = client.get(f"/api/v1/models/{a.id}", headers=auth_headers).json()
    assert detail["tags"] == []


def test_batch_set_revision_labels(
    client: TestClient, auth_headers: dict[str, str], db_session: Session
) -> None:
    model = _model(db_session)
    file_row = _file(db_session, model)

    resp = client.patch(
        "/api/v1/models/batch/revision-labels",
        json={"file_ids": [file_row.id], "revision_label": "Batch label"},
        headers=auth_headers,
    )
    assert resp.status_code == 200
    assert resp.json()["succeeded_ids"] == [file_row.id]
    db_session.refresh(file_row)
    assert file_row.revision_label == "Batch label"


def test_batch_set_revision_labels_rejects_non_gcode(
    client: TestClient, auth_headers: dict[str, str], db_session: Session
) -> None:
    model = _model(db_session)
    mesh = _file(db_session, model, file_type=FileType.STL)

    resp = client.patch(
        "/api/v1/models/batch/revision-labels",
        json={"file_ids": [mesh.id], "revision_label": "x"},
        headers=auth_headers,
    )
    assert resp.status_code == 400
    assert resp.json()["detail"] == "revision_not_supported"


def test_batch_set_revision_labels_unknown_file_404(
    client: TestClient, auth_headers: dict[str, str]
) -> None:
    resp = client.patch(
        "/api/v1/models/batch/revision-labels",
        json={"file_ids": [999999], "revision_label": "x"},
        headers=auth_headers,
    )
    assert resp.status_code == 404
    assert resp.json()["detail"] == "file_not_found"


def test_batch_delete_models(
    client: TestClient, auth_headers: dict[str, str], db_session: Session
) -> None:
    model = _model(db_session)
    resp = client.post(
        "/api/v1/models/batch/delete",
        json={"model_ids": [model.id]},
        headers=auth_headers,
    )
    assert resp.status_code == 200
    assert resp.json()["succeeded_ids"] == [model.id]
    db_session.refresh(model)
    assert model.deleted_at is not None


def test_star_unknown_model_returns_404(
    client: TestClient, auth_headers: dict[str, str]
) -> None:
    resp = client.put("/api/v1/models/999999/star", headers=auth_headers)
    assert resp.status_code == 404
    assert resp.json()["detail"] == "model_not_found"


def test_batch_move_root_model_denied_for_non_superuser(
    client: TestClient, db_session: Session
) -> None:
    model = _model(db_session)  # root model, no collection
    dest = Collection(name="Dest", slug="dest", path="dest")
    db_session.add(dest)
    db_session.commit()
    db_session.refresh(dest)
    user = _regular_user(db_session)
    db_session.add(
        CollectionPermission(
            user_id=user.id, collection_id=dest.id, role=CollectionRole.EDIT
        )
    )
    db_session.commit()

    resp = client.post(
        "/api/v1/models/batch/move",
        json={"model_ids": [model.id], "collection": "dest"},
        headers=_headers_for(user),
    )
    assert resp.status_code == 403
    assert resp.json()["detail"] == "root_collection_admin_required"


def test_batch_move_unknown_destination_denied_for_non_superuser(
    client: TestClient, db_session: Session
) -> None:
    user = _regular_user(db_session)
    model = _model(db_session)
    resp = client.post(
        "/api/v1/models/batch/move",
        json={"model_ids": [model.id], "collection": "does/not/exist"},
        headers=_headers_for(user),
    )
    assert resp.status_code == 403
    assert resp.json()["detail"] == "collection_permission_denied"


def test_batch_move_to_root_as_superuser(
    client: TestClient, auth_headers: dict[str, str], db_session: Session
) -> None:
    model = _model(db_session)
    collection = Collection(name="Brackets", slug="brackets", path="brackets")
    db_session.add(collection)
    db_session.commit()
    db_session.refresh(collection)
    model.collection_id = collection.id
    db_session.add(model)
    db_session.commit()

    resp = client.post(
        "/api/v1/models/batch/move",
        json={"model_ids": [model.id], "collection": ""},
        headers=auth_headers,
    )
    assert resp.status_code == 200
    db_session.refresh(model)
    assert model.collection_id is None


def test_batch_move_into_existing_destination_checks_role(
    client: TestClient, auth_headers: dict[str, str], db_session: Session
) -> None:
    model = _model(db_session)
    collection = Collection(name="Brackets", slug="brackets", path="brackets")
    db_session.add(collection)
    db_session.commit()
    db_session.refresh(collection)

    resp = client.post(
        "/api/v1/models/batch/move",
        json={"model_ids": [model.id], "collection": "brackets"},
        headers=auth_headers,
    )
    assert resp.status_code == 200
    db_session.refresh(model)
    assert model.collection_id == collection.id


def test_batch_move_denies_model_in_uneditable_source_collection(
    client: TestClient, db_session: Session
) -> None:
    source = Collection(name="Source", slug="source", path="source")
    dest = Collection(name="Dest", slug="dest", path="dest")
    db_session.add(source)
    db_session.add(dest)
    db_session.commit()
    db_session.refresh(source)
    db_session.refresh(dest)
    model = _model(db_session, slug="stuck")
    model.collection_id = source.id
    db_session.add(model)
    db_session.commit()

    user = _regular_user(db_session)
    db_session.add(
        CollectionPermission(
            user_id=user.id, collection_id=dest.id, role=CollectionRole.EDIT
        )
    )
    db_session.commit()

    resp = client.post(
        "/api/v1/models/batch/move",
        json={"model_ids": [model.id], "collection": "dest"},
        headers=_headers_for(user),
    )
    assert resp.status_code == 403
    assert resp.json()["detail"] == "collection_permission_denied"


def test_batch_set_revision_labels_reports_unexpected_error(
    client: TestClient, auth_headers: dict[str, str], db_session: Session, monkeypatch
) -> None:
    model = _model(db_session)
    file_row = _file(db_session, model)

    def fake_set_revision_labels(*_a, **_k):
        raise RuntimeError("boom")

    monkeypatch.setattr(
        "app.api.v1.models.model_views.set_revision_labels", fake_set_revision_labels
    )
    with pytest.raises(RuntimeError, match="boom"):
        client.patch(
            "/api/v1/models/batch/revision-labels",
            json={"file_ids": [file_row.id], "revision_label": "x"},
            headers=auth_headers,
        )


def test_batch_tag_remove_treats_a_blank_entry_as_the_fallback_slug(
    client: TestClient, auth_headers: dict[str, str], db_session: Session
) -> None:
    """`slugify` never returns empty, so a blank remove entry is not skipped.

    It resolves to the fallback slug `model`. See the findings section of
    `reports/22-test-overhaul-report.md`: the guard that looks like it skips
    blanks (`if not slug: continue`) cannot fire, and the previous test for it
    asserted only the 200 it would have returned either way.
    """
    from app.services import taxonomy

    model = _model(db_session)
    tag = taxonomy.resolve_or_create_tags_in_transaction(db_session, ["model"])[0]
    db_session.commit()
    client.post(
        "/api/v1/models/batch/tags",
        json={"model_ids": [model.id], "add": ["model"], "remove": []},
        headers=auth_headers,
    )

    response = client.post(
        "/api/v1/models/batch/tags",
        json={"model_ids": [model.id], "add": [], "remove": ["   "]},
        headers=auth_headers,
    )

    assert response.status_code == 200, response.text
    detail = client.get(f"/api/v1/models/{model.id}", headers=auth_headers).json()
    assert tag.slug not in detail["tags"]
