"""Enum-valued columns: TEXT, a CHECK constraint, and Alembic keeping them in step.

No database-native enum types. A PostgreSQL ``ENUM`` is a type of its own:
adding a value is ``ALTER TYPE … ADD VALUE``, which cannot run inside the
transaction a migration runs in on older servers and can never be undone, and
SQLite has no such type at all. Instead an enum column is

* ``TEXT`` in both databases, read back as the Python enum member (an unknown
  value raises instead of flowing on as a bare string), and
* one named ``CHECK (<column> IN (…))`` constraint listing exactly the enum's
  values, so the database refuses what the type refuses.

Alembic compares neither enum values nor CHECK constraints on an existing
table, so adding a member (or a CHECK) would otherwise generate no migration.
``compare_check_constraints`` closes that: it reflects the table's named CHECK
constraints, creates each one the model names that the database lacks, and
drops and re-creates an enum CHECK whose values differ from the enum (inside
``batch_alter_table`` on SQLite, which rebuilds the table to change a
constraint). Adding a member is therefore an ordinary autogenerated migration,
and ``test_models_versus_chain`` fails until it exists. A reflected CHECK the
model does not name is left alone: its SQL text is dialect-rewritten, so only
its presence and, for an enum, its values are compared.
"""

from __future__ import annotations

import re
from enum import Enum
from typing import Any

from alembic.autogenerate import comparators
from alembic.operations import ops
from sqlalchemy import CheckConstraint, Text
from sqlalchemy.types import TypeDecorator

# ``ck_<table>_<column>_values`` once the metadata naming convention applies.
_SUFFIX = "_values"
_QUOTED = re.compile(r"'((?:[^']|'')*)'")


class EnumText(TypeDecorator):
    """TEXT that binds and loads members of ``enum`` and nothing else."""

    impl = Text
    cache_ok = True

    def __init__(self, enum: type[Enum]) -> None:
        super().__init__()
        self.enum = enum

    def process_bind_param(self, value: Any, dialect: Any) -> str | None:
        if value is None:
            return None
        return self.enum(value).value

    def process_result_value(self, value: Any, dialect: Any) -> Enum | None:
        if value is None:
            return None
        return self.enum(value)


def enum_check(column: str, enum: type[Enum]) -> CheckConstraint:
    """The CHECK constraint that limits ``column`` to ``enum``'s values."""
    listed = ", ".join(_quote(member.value) for member in enum)
    return CheckConstraint(
        f"{column} IN ({listed})",
        name=f"{column}{_SUFFIX}",
        info={"enum_values": frozenset(member.value for member in enum)},
    )


def _quote(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def _values(sqltext: str) -> frozenset[str]:
    return frozenset(match.replace("''", "'") for match in _QUOTED.findall(sqltext))


@comparators.dispatch_for("table")
def compare_check_constraints(
    autogen_context, modify_ops, schemaname, tname, conn_table, metadata_table
) -> None:
    """Create missing named CHECKs; re-create enum CHECKs whose values drifted."""
    if conn_table is None or metadata_table is None:
        # A new table is created with its constraints; a dropped one goes whole.
        return
    wanted = {
        constraint.name: constraint
        for constraint in metadata_table.constraints
        if isinstance(constraint, CheckConstraint) and constraint.name
    }
    if not wanted:
        return
    inspector = autogen_context.inspector
    reflected = {
        row["name"]: _values(str(row["sqltext"]))
        for row in inspector.get_check_constraints(tname, schema=schemaname)
        if row.get("name")
    }
    for name, constraint in sorted(wanted.items()):
        present = reflected.get(name)
        enum_values = constraint.info.get("enum_values")
        if present is not None and (enum_values is None or present == enum_values):
            continue
        if present is not None:
            modify_ops.ops.append(ops.DropConstraintOp.from_constraint(constraint))
        modify_ops.ops.append(ops.CreateCheckConstraintOp.from_constraint(constraint))
