"""similarity runs are advanced by the job engine [confirmed data-dropping, not a rename: similarity_runs.last_activity_at, similarity_runs.lease_expires_at, similarity_runs.lease_token]

Revision ID: 0906f5b806b5
Revises: a0c0a39f9d66
Create Date: 2026-09-24 12:08:58.006907

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0906f5b806b5'
down_revision: Union[str, Sequence[str], None] = 'a0c0a39f9d66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('similarity_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('writer', sa.String(length=128), nullable=True))
        batch_op.drop_index(batch_op.f('ix_similarity_run_claim'))
        batch_op.create_index('ix_similarity_run_state', ['state'], unique=False)
        batch_op.drop_column('last_activity_at')
        batch_op.drop_column('lease_expires_at')
        batch_op.drop_column('lease_token')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Reflected from SQLite: portable types so this also runs on PostgreSQL,
    # and a default so existing runs can take the restored NOT NULL column.
    with op.batch_alter_table('similarity_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lease_token', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('lease_expires_at', sa.DateTime(), nullable=True))
        batch_op.add_column(
            sa.Column(
                'last_activity_at',
                sa.DateTime(),
                nullable=False,
                server_default=sa.text('CURRENT_TIMESTAMP'),
            )
        )
        batch_op.drop_index('ix_similarity_run_state')
        batch_op.create_index(batch_op.f('ix_similarity_run_claim'), ['state', 'lease_expires_at'], unique=False)
        batch_op.drop_column('writer')

    # ### end Alembic commands ###
