"""job engine enums are text with check constraints [confirmed data-dropping, not a rename: reconcile_cursors.state_json]

Revision ID: 0fee449176a0
Revises: ca576b5337d2
Create Date: 2026-09-25 01:21:33.325274

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0fee449176a0'
down_revision: Union[str, Sequence[str], None] = 'ca576b5337d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artifact_derivatives', schema=None) as batch_op:
        batch_op.alter_column('kind',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('failure_reason',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.create_check_constraint(batch_op.f('ck_artifact_derivatives_kind_values'), "kind IN ('metadata', 'thumbnail', 'toolpath')")
        batch_op.create_check_constraint(batch_op.f('ck_artifact_derivatives_reason_iff_failed_or_skipped'), "(state IN ('failed', 'skipped')) = (failure_reason IS NOT NULL)")
        batch_op.create_check_constraint(batch_op.f('ck_artifact_derivatives_retry_only_when_failed'), "next_attempt_at IS NULL OR state = 'failed'")
        batch_op.create_check_constraint(batch_op.f('ck_artifact_derivatives_state_values'), "state IN ('queued', 'running', 'ready', 'skipped', 'failed', 'cancelled')")

    with op.batch_alter_table('derivative_regenerations', schema=None) as batch_op:
        batch_op.alter_column('kind',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.create_check_constraint(batch_op.f('ck_derivative_regenerations_kind_values'), "kind IN ('metadata', 'thumbnail', 'toolpath')")

    with op.batch_alter_table('ingest_requests', schema=None) as batch_op:
        batch_op.alter_column('kind',
               existing_type=sa.VARCHAR(length=24),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.create_check_constraint(batch_op.f('ck_ingest_requests_kind_values'), "kind IN ('upload', 'url', 'archive_inspect', 'archive_selection', 'url_selection', 'collection')")

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.alter_column('kind',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('priority',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.create_check_constraint(batch_op.f('ck_jobs_kind_values'), "kind IN ('administration.audit', 'backups.automatic', 'backups.create', 'backups.retry_destination', 'backups.trash_gc', 'derivatives.gcode', 'derivatives.mesh', 'derivatives.toolpath', 'identity.retention', 'inference.model_download', 'ingestion.archive_inspect', 'ingestion.archive_selection', 'ingestion.artifact_upload', 'ingestion.collection', 'ingestion.inbox_import', 'ingestion.inbox_resolve', 'ingestion.inbox_retention', 'ingestion.library_import', 'ingestion.upload', 'ingestion.upload_recovery', 'ingestion.url', 'ingestion.url_selection', 'notifications.deliver', 'notifications.retention', 'printing.dispatch', 'search.caption', 'search.caption_queue', 'search.expand', 'search.generation', 'search.index', 'search.project', 'search.repair', 'similarity.analyze', 'sources.scan', 'storage.inventory', 'storage.migrate', 'work.housekeeping')")
        batch_op.create_check_constraint(batch_op.f('ck_jobs_priority_values'), "priority IN ('interactive', 'backfill')")
        batch_op.create_check_constraint(batch_op.f('ck_jobs_state_values'), "state IN ('queued', 'running', 'interrupted', 'completed', 'failed', 'cancelled')")

    with op.batch_alter_table('reconcile_cursors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pass_priority', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('idle_since', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('idle_until', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('scan_high_water', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('scan_position', sa.Integer(), server_default='0', nullable=False))
        batch_op.alter_column('source',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.create_check_constraint(batch_op.f('ck_reconcile_cursors_holder_with_expiry'), '(holder IS NULL) = (holder_expires_at IS NULL)')
        batch_op.create_check_constraint(batch_op.f('ck_reconcile_cursors_idle_window_complete'), '(idle_since IS NULL) = (idle_until IS NULL)')
        batch_op.create_check_constraint(batch_op.f('ck_reconcile_cursors_pass_priority_values'), "pass_priority IN ('interactive', 'backfill')")
        batch_op.create_check_constraint(batch_op.f('ck_reconcile_cursors_pass_queued_with_priority'), '(pass_queued_at IS NULL) = (pass_priority IS NULL)')
        batch_op.create_check_constraint(batch_op.f('ck_reconcile_cursors_source_values'), "source IN ('administration.audit', 'backups.automatic', 'backups.create', 'backups.retry_destination', 'backups.trash_gc', 'derivatives.gcode', 'derivatives.mesh', 'derivatives.toolpath', 'identity.retention', 'inference.model_download', 'ingestion.archive_inspect', 'ingestion.archive_selection', 'ingestion.artifact_upload', 'ingestion.collection', 'ingestion.inbox_import', 'ingestion.inbox_resolve', 'ingestion.inbox_retention', 'ingestion.library_import', 'ingestion.upload', 'ingestion.upload_recovery', 'ingestion.url', 'ingestion.url_selection', 'notifications.deliver', 'notifications.retention', 'printing.dispatch', 'search.caption', 'search.caption_queue', 'search.expand', 'search.generation', 'search.index', 'search.project', 'search.repair', 'similarity.analyze', 'sources.scan', 'storage.inventory', 'storage.migrate', 'work.housekeeping')")
        batch_op.drop_column('state_json')

    with op.batch_alter_table('work_executors', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.create_check_constraint(batch_op.f('ck_work_executors_role_values'), "role IN ('all', 'api', 'worker')")

    with op.batch_alter_table('work_lane_overrides', schema=None) as batch_op:
        batch_op.alter_column('lane',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.create_check_constraint(batch_op.f('ck_work_lane_overrides_lane_values'), "lane IN ('captions', 'derive.light', 'derive.native', 'expansion', 'ingest', 'maintenance', 'network', 'notify', 'printing', 'reconcile', 'search', 'similarity')")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_lane_overrides', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('ck_work_lane_overrides_lane_values'), type_='check')
        batch_op.alter_column('lane',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)

    with op.batch_alter_table('work_executors', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('ck_work_executors_role_values'), type_='check')
        batch_op.alter_column('role',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)

    with op.batch_alter_table('reconcile_cursors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state_json', sa.TEXT(), nullable=False))
        batch_op.drop_constraint(batch_op.f('ck_reconcile_cursors_source_values'), type_='check')
        batch_op.drop_constraint(batch_op.f('ck_reconcile_cursors_pass_queued_with_priority'), type_='check')
        batch_op.drop_constraint(batch_op.f('ck_reconcile_cursors_pass_priority_values'), type_='check')
        batch_op.drop_constraint(batch_op.f('ck_reconcile_cursors_idle_window_complete'), type_='check')
        batch_op.drop_constraint(batch_op.f('ck_reconcile_cursors_holder_with_expiry'), type_='check')
        batch_op.alter_column('source',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
        batch_op.drop_column('scan_position')
        batch_op.drop_column('scan_high_water')
        batch_op.drop_column('idle_until')
        batch_op.drop_column('idle_since')
        batch_op.drop_column('pass_priority')

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('ck_jobs_state_values'), type_='check')
        batch_op.drop_constraint(batch_op.f('ck_jobs_priority_values'), type_='check')
        batch_op.drop_constraint(batch_op.f('ck_jobs_kind_values'), type_='check')
        batch_op.alter_column('state',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)
        batch_op.alter_column('priority',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)
        batch_op.alter_column('kind',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)

    with op.batch_alter_table('ingest_requests', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('ck_ingest_requests_kind_values'), type_='check')
        batch_op.alter_column('kind',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=24),
               existing_nullable=False)

    with op.batch_alter_table('derivative_regenerations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('ck_derivative_regenerations_kind_values'), type_='check')
        batch_op.alter_column('kind',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)

    with op.batch_alter_table('artifact_derivatives', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('ck_artifact_derivatives_state_values'), type_='check')
        batch_op.drop_constraint(batch_op.f('ck_artifact_derivatives_retry_only_when_failed'), type_='check')
        batch_op.drop_constraint(batch_op.f('ck_artifact_derivatives_reason_iff_failed_or_skipped'), type_='check')
        batch_op.drop_constraint(batch_op.f('ck_artifact_derivatives_kind_values'), type_='check')
        batch_op.alter_column('failure_reason',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.alter_column('state',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)
        batch_op.alter_column('kind',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)

    # ### end Alembic commands ###
