"""add Orca native context

Revision ID: 489225f7b46b
Revises: c46bd16d3080
Create Date: 2026-09-26 22:46:57.967984

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "489225f7b46b"
down_revision: Union[str, Sequence[str], None] = "c46bd16d3080"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("metadata", schema=None) as batch_op:
        batch_op.add_column(sa.Column("native_context_json", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("metadata", schema=None) as batch_op:
        batch_op.drop_column("native_context_json")

    # ### end Alembic commands ###
