"""backup runs record the job that built them

A run now names its Job, and the next attempt of that Job settles whatever the
previous one left open. Runs from before this revision name no Job, so a run
an interrupted process left ``running`` would never settle: the upgrade (which
runs with the application stopped, so nothing can still be publishing)
settles them here, as the old list-time repair did.

Revision ID: 594452a753fe
Revises: 0906f5b806b5
Create Date: 2026-09-24 12:19:50.912748

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '594452a753fe'
down_revision: Union[str, Sequence[str], None] = '0906f5b806b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_INTERRUPTED = "backup_publication_interrupted"


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backup_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_id', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_backup_runs_job_id'), ['job_id'], unique=False)

    # ### end Alembic commands ###
    bind = op.get_bind()
    params = {"error": _INTERRUPTED}
    bind.execute(
        sa.text(
            "UPDATE backup_destination_results "
            "SET outcome = 'failed', error_code = :error, "
            "updated_at = CURRENT_TIMESTAMP "
            "WHERE outcome = 'publishing' OR (outcome = 'pending' AND run_id IN "
            "(SELECT id FROM backup_runs WHERE outcome = 'running'))"
        ),
        params,
    )
    bind.execute(
        sa.text(
            "UPDATE backup_retry_attempts "
            "SET outcome = CASE WHEN EXISTS (SELECT 1 FROM "
            "backup_destination_results r WHERE r.id = "
            "backup_retry_attempts.destination_result_id AND r.outcome = "
            "'completed') THEN 'completed' ELSE 'failed' END, "
            "error_code = CASE WHEN EXISTS (SELECT 1 FROM "
            "backup_destination_results r WHERE r.id = "
            "backup_retry_attempts.destination_result_id AND r.outcome = "
            "'completed') THEN NULL ELSE :error END, "
            "finished_at = CURRENT_TIMESTAMP "
            "WHERE outcome = 'running'"
        ),
        params,
    )
    bind.execute(
        sa.text(
            "UPDATE backup_runs SET outcome = CASE "
            "WHEN NOT EXISTS (SELECT 1 FROM backup_destination_results r "
            "WHERE r.run_id = backup_runs.id) THEN 'failed' "
            "WHEN NOT EXISTS (SELECT 1 FROM backup_destination_results r "
            "WHERE r.run_id = backup_runs.id AND r.outcome <> 'completed') "
            "THEN 'completed' "
            "WHEN EXISTS (SELECT 1 FROM backup_destination_results r "
            "WHERE r.run_id = backup_runs.id AND r.outcome = 'completed') "
            "THEN 'partial' ELSE 'failed' END, "
            "finished_at = CURRENT_TIMESTAMP "
            "WHERE outcome = 'running'"
        )
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backup_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backup_runs_job_id'))
        batch_op.drop_column('job_id')

    # ### end Alembic commands ###
