"""Rename background jobs to Jobs, and their references to ``job_id``.

The job engine replaces the in-process job registry. Its user-visible record is
the ``jobs`` table, which is the old ``background_jobs`` table renamed, so
staging leases, Pending Imports and upload sessions keep pointing at the rows
they point at today.

No execution survives an upgrade: the registry that ran them is gone, and a Job
never carries replayable input. So every Job still pending or running becomes a
failed Job saying so, and the staging leases it owned expire now, which lets
staging cleanup reclaim their files the way it reclaims any expired lease. Old
status payloads are replaced by ones the new status shape understands; the old
payloads' progress and error details are not carried over.

Every legacy kind is renamed to the Job Definition that now does its work, so
the upgraded history reads as the closed set of kinds the database allows. A
``thumbnail_rebuild`` Job has no successor (a derivative retry is not a Job of
its own) and nothing points at one, so those rows are dropped.

The data work is plain SQL so the revision also renders offline.

Renames are written by hand, outside a batch block: a schema differ sees a
rename as a drop plus an add, and SQLite renames in place without a rebuild.
The next revision, which is autogenerated, reshapes the renamed table.

Revision ID: 73abd9b883d9
Revises: 0118bda3e719
Create Date: 2026-09-24 02:39:04.094285
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "73abd9b883d9"
down_revision: str | Sequence[str] | None = "0118bda3e719"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_REFERENCES = ("staging_leases", "inbox_items", "artifact_upload_sessions")

_JOBS = sa.table(
    "background_jobs",
    sa.column("id", sa.String),
    sa.column("kind", sa.String),
    sa.column("state", sa.String),
    sa.column("status_json", sa.Text),
    sa.column("finished_at", sa.DateTime),
    sa.column("updated_at", sa.DateTime),
)
_LEASES = sa.table(
    "staging_leases",
    sa.column("background_job_id", sa.String),
    sa.column("expires_at", sa.DateTime),
)


# Every kind the retired registry wrote, and the definition that does its work.
_KINDS = {
    "ingest": "ingestion.upload",
    "gcode": "ingestion.upload",
    "model": "ingestion.upload",
    "artifact": "ingestion.upload",
    "url": "ingestion.url",
    "archive_manifest": "ingestion.archive_inspect",
    "archive": "ingestion.archive_selection",
    "url_selection": "ingestion.url_selection",
    "collection": "ingestion.collection",
    "library_import": "ingestion.library_import",
    "pending_import": "ingestion.inbox_import",
    "external_scan": "sources.scan",
    "ai_search": "search.generation",
    "ai_caption": "search.caption",
    "model_download": "inference.model_download",
}


def _rename_kinds() -> None:
    op.execute(_JOBS.delete().where(_JOBS.c.kind == "thumbnail_rebuild"))
    for legacy, current in _KINDS.items():
        op.execute(_JOBS.update().where(_JOBS.c.kind == legacy).values(kind=current))


def _settle_jobs() -> None:
    now = sa.func.current_timestamp()
    op.execute(
        _JOBS.update()
        .where(_JOBS.c.state.in_(("pending", "running")))
        .values(
            state="failed",
            status_json='{"error":"interrupted_by_upgrade"}',
            finished_at=now,
            updated_at=now,
        )
    )
    op.execute(
        _JOBS.update()
        .where(_JOBS.c.state == "failed")
        .where(_JOBS.c.status_json != '{"error":"interrupted_by_upgrade"}')
        .values(status_json='{"error":"failed_before_upgrade"}')
    )
    op.execute(
        _JOBS.update().where(_JOBS.c.state == "completed").values(status_json="{}")
    )
    op.execute(
        _LEASES.update()
        .where(_LEASES.c.background_job_id.is_not(None))
        .where(_LEASES.c.expires_at > now)
        .values(expires_at=now)
    )


def upgrade() -> None:
    _settle_jobs()
    _rename_kinds()
    op.rename_table("background_jobs", "jobs")
    for table in _REFERENCES:
        op.alter_column(table, "background_job_id", new_column_name="job_id")


def downgrade() -> None:
    for table in _REFERENCES:
        op.alter_column(table, "job_id", new_column_name="background_job_id")
    op.rename_table("jobs", "background_jobs")
