"""drop native compute slots

Revision ID: a0c0a39f9d66
Revises: a83ea973fad4
Create Date: 2026-09-24 11:19:04.761014

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a0c0a39f9d66"
down_revision: Union[str, Sequence[str], None] = "a83ea973fad4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("native_compute_slots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_native_compute_slots_lease_expires_at"))
        batch_op.drop_index(batch_op.f("ix_native_compute_slots_lease_token"))
        batch_op.drop_index(batch_op.f("ix_native_compute_slots_slot_number"))

    op.drop_table("native_compute_slots")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Reflected from SQLite; the column types are the portable ones so the
    # downgrade also runs on PostgreSQL.
    op.create_table(
        "native_compute_slots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slot_number", sa.Integer(), nullable=False),
        sa.Column("lease_token", sa.String(length=64), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_native_compute_slots")),
    )
    with op.batch_alter_table("native_compute_slots", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_native_compute_slots_slot_number"),
            ["slot_number"],
            unique=True,
        )
        batch_op.create_index(
            batch_op.f("ix_native_compute_slots_lease_token"),
            ["lease_token"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_native_compute_slots_lease_expires_at"),
            ["lease_expires_at"],
            unique=False,
        )

    # ### end Alembic commands ###
