"""defer search projection independently of imports

Revision ID: a23d2e57ff0c
Revises: b49f72e927c9
Create Date: 2026-09-20 17:41:07.451911

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a23d2e57ff0c'
down_revision: Union[str, Sequence[str], None] = 'b49f72e927c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_projection_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_kind', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('cursor_kind', sa.String(length=32), nullable=False),
    sa.Column('cursor_id', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('source_id > 0', name=op.f('ck_search_projection_requests_source_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_search_projection_requests')),
    sa.UniqueConstraint('source_kind', 'source_id', name='uq_search_projection_source')
    )
    with op.batch_alter_table('search_projection_requests', schema=None) as batch_op:
        batch_op.create_index('ix_search_projection_due', ['next_attempt_at', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_projection_requests', schema=None) as batch_op:
        batch_op.drop_index('ix_search_projection_due')

    op.drop_table('search_projection_requests')
    # ### end Alembic commands ###
