#!/usr/bin/env python3
"""
PrintStash OrcaSlicer post-processing hook.

Configure in OrcaSlicer:
    Process → Others → Post-processing scripts:
        /usr/bin/python3 /path/to/printstash_orca_push.py \
            --url https://printstash.example.com \
            --username YOUR_USERNAME \
            --api-key psk_YOUR_KEY \
            --collection "Functional/Brackets"

OrcaSlicer appends the exported .gcode path automatically as the final argv.
Setup, native marker guidance, mapping modes, and the API contract:
    https://github.com/xiao-villamor/PrintStash/blob/main/docs/orcaslicer.md

Design rules (do not break):
  * stdlib only — no `pip install requests` for end users.
  * Always exit 0 — a PrintStash outage MUST NEVER block the slicing/export flow.
  * Logs to ~/.printstash_orca_push.log for debugging.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import logging
import mimetypes
import os
import re
import sys
import time
import uuid
from pathlib import Path
from typing import Iterator, Mapping
from urllib import request as urlrequest
from urllib.error import HTTPError, URLError
from zipfile import BadZipFile, ZipFile, is_zipfile

LOG_PATH = Path.home() / ".printstash_orca_push.log"
log = logging.getLogger("printstash_orca_push")
log.addHandler(logging.NullHandler())

_OBJECT_LABEL_RE = re.compile(
    r"^;\s*printing object\s+(.+?)\s+id:(\S+)\s+copy\s+(\d+)\s*$",
    re.IGNORECASE,
)
_GENERATED_RE = re.compile(r"^;\s*generated by\s+OrcaSlicer\s+([^\s]+)", re.IGNORECASE)
_MARKER_RE = re.compile(r"^;\s*printstash:([a-z_]+)\s*=\s*(.*?)\s*$", re.IGNORECASE)
_CONFIG_RE = re.compile(r"^;\s*([a-zA-Z0-9_]+)\s*=\s*(.*?)\s*$")
_TIME_RE = re.compile(r"^;\s*TIME\s*:\s*(\d+(?:\.\d+)?)\s*$", re.IGNORECASE)
_STAT_PATTERNS = {
    "filament_weight_g": re.compile(
        r"^;\s*(?:total )?filament used \[g\]\s*=\s*([\d.]+)", re.IGNORECASE
    ),
    "filament_length_mm": re.compile(
        r"^;\s*(?:total )?filament (?:used|length) \[mm\]\s*=\s*([\d.]+)",
        re.IGNORECASE,
    ),
    "filament_cost": re.compile(
        r"^;\s*(?:total )?filament cost\s*=\s*([\d.]+)", re.IGNORECASE
    ),
}
_MARKER_ALIASES = {
    "input_filename": "source_filename",
    "num_objects": "object_count",
    "num_instances": "instance_count",
}
_SOURCE_SUFFIXES = (".stl", ".3mf", ".obj", ".step", ".stp", ".dxf")


def configure_logging(path: Path) -> None:
    """Write hook diagnostics to one explicit local file."""
    path.parent.mkdir(parents=True, exist_ok=True)
    handler = logging.FileHandler(path, encoding="utf-8")
    handler.setFormatter(logging.Formatter("%(asctime)s [%(levelname)s] %(message)s"))
    log.handlers.clear()
    log.addHandler(handler)
    log.setLevel(logging.INFO)
    log.propagate = False


def _clean(value: str | None) -> str | None:
    if value is None:
        return None
    cleaned = value.strip().strip('"')
    if not cleaned or (cleaned.startswith("{") and cleaned.endswith("}")):
        return None
    return cleaned


def _split(value: str | None) -> list[str]:
    cleaned = _clean(value)
    if not cleaned:
        return []
    return [
        part.strip().strip('"') for part in re.split(r"[;,]", cleaned) if part.strip()
    ]


def _as_count(value: str | None) -> int | None:
    cleaned = _clean(value)
    if cleaned is None:
        return None
    try:
        count = int(cleaned)
    except ValueError:
        return None
    return count if 0 <= count <= 100_000 else None


def _source_filename(value: str | None) -> str | None:
    cleaned = _clean(value)
    if cleaned is None:
        return None
    filename = Path(cleaned.replace("\\", "/")).name
    return filename if filename.lower().endswith(_SOURCE_SUFFIXES) else None


def _is_gcode_3mf(path: Path) -> bool:
    return path.name.lower().endswith(".gcode.3mf") and is_zipfile(path)


def _gcode_member(archive: ZipFile) -> str | None:
    candidates = sorted(
        info.filename
        for info in archive.infolist()
        if not info.is_dir()
        and info.filename.lower().startswith("metadata/")
        and info.filename.lower().endswith(".gcode")
    )
    return candidates[0] if candidates else None


def _native_lines(path: Path) -> Iterator[str]:
    if _is_gcode_3mf(path):
        try:
            with ZipFile(path) as archive:
                member = _gcode_member(archive)
                if member is None:
                    return
                with archive.open(member) as stream:
                    for raw_line in stream:
                        yield raw_line.decode("utf-8", errors="replace").rstrip("\r\n")
        except (BadZipFile, OSError):
            return
        return
    try:
        with path.open("r", encoding="utf-8", errors="replace") as stream:
            for line in stream:
                yield line.rstrip("\r\n")
    except OSError:
        return


def _archive_project_name(path: Path) -> str | None:
    if not _is_gcode_3mf(path):
        return None
    try:
        with ZipFile(path) as archive:
            for info in archive.infolist():
                if info.filename.lower().endswith("model_settings.config"):
                    text = archive.read(info, pwd=None).decode(
                        "utf-8", errors="replace"
                    )
                    match = re.search(r'<metadata key="name" value="([^"]+)"', text)
                    if match:
                        return _clean(match.group(1))
    except (BadZipFile, KeyError, OSError):
        return None
    return None


def extract_native_context(gcode: Path, environ: Mapping[str, str]) -> dict:
    """Normalize native Orca facts once for naming, lineage, upload, and logs."""
    markers: dict[str, str] = {}
    config: dict[str, str] = {}
    labels: dict[tuple[str, str, int], dict[str, object]] = {}
    stats: dict[str, int | float] = {}
    slicer_version: str | None = None

    for line in _native_lines(gcode):
        if match := _MARKER_RE.match(line):
            key = _MARKER_ALIASES.get(match.group(1).lower(), match.group(1).lower())
            value = _clean(match.group(2))
            if value is not None:
                markers[key] = value
            continue
        if match := _OBJECT_LABEL_RE.match(line):
            name, object_id, copy_index_raw = match.groups()
            copy_index = int(copy_index_raw)
            labels[(name, object_id, copy_index)] = {
                "name": name,
                "object_id": object_id,
                "copy_index": copy_index,
            }
            continue
        if slicer_version is None and (match := _GENERATED_RE.match(line)):
            slicer_version = match.group(1)
        if match := _TIME_RE.match(line):
            stats.setdefault("estimated_time_s", int(float(match.group(1))))
        for name, pattern in _STAT_PATTERNS.items():
            if match := pattern.match(line):
                stats[name] = float(match.group(1))
        if match := _CONFIG_RE.match(line):
            config[match.group(1).lower()] = match.group(2)

    object_labels = list(labels.values())
    object_ids = {str(label["object_id"]) for label in object_labels}
    label_object_count = len(object_ids) if object_ids else None
    label_instance_count = len(object_labels) if object_labels else None
    runtime_filename = _source_filename(environ.get("SLIC3R_INPUT_FILENAME"))
    marker_filename = _source_filename(markers.get("source_filename"))
    label_filename = (
        str(object_labels[0]["name"])
        if label_object_count == 1 and object_labels
        else None
    )
    label_filename = _source_filename(label_filename)
    source_filename = runtime_filename or marker_filename or label_filename

    runtime_object_count = _as_count(environ.get("SLIC3R_NUM_OBJECTS"))
    marker_object_count = _as_count(markers.get("object_count"))
    reported_object_count = runtime_object_count or marker_object_count
    object_count = (
        max(
            count
            for count in (reported_object_count, label_object_count)
            if count is not None
        )
        if reported_object_count is not None or label_object_count is not None
        else None
    )
    runtime_instance_count = _as_count(environ.get("SLIC3R_NUM_INSTANCES"))
    marker_instance_count = _as_count(markers.get("instance_count"))
    reported_instance_count = runtime_instance_count or marker_instance_count
    instance_count = (
        max(
            count
            for count in (reported_instance_count, label_instance_count)
            if count is not None
        )
        if reported_instance_count is not None or label_instance_count is not None
        else None
    )
    if object_count == 1 and source_filename:
        classification = "single_object"
    elif object_count is not None and object_count > 1:
        classification = "multi_object"
    else:
        classification = "unknown"

    field_sources: dict[str, str] = {}

    def sourced(path: str, runtime: str | None, fallback: str | None, source: str):
        value = _clean(runtime) or _clean(fallback)
        if value is not None:
            field_sources[path] = "runtime" if _clean(runtime) is not None else source
        return value

    if source_filename:
        if runtime_filename:
            field_sources["source.filename"] = "runtime"
        elif marker_filename:
            field_sources["source.filename"] = "gcode_marker"
        else:
            field_sources["source.filename"] = "gcode_object_label"
    if object_labels:
        field_sources["source.object_labels"] = "gcode_object_label"
    if object_count is not None:
        if runtime_object_count == object_count:
            field_sources["source.object_count"] = "runtime"
        elif marker_object_count == object_count:
            field_sources["source.object_count"] = "gcode_marker"
        else:
            field_sources["source.object_count"] = "gcode_object_label"
    if instance_count is not None:
        if runtime_instance_count == instance_count:
            field_sources["source.instance_count"] = "runtime"
        elif marker_instance_count == instance_count:
            field_sources["source.instance_count"] = "gcode_marker"
        else:
            field_sources["source.instance_count"] = "gcode_object_label"

    runtime_first_object = _clean(environ.get("SLIC3R_FIRST_OBJECT_NAME"))
    marker_first_object = _clean(markers.get("first_object_name"))
    first_object_name = runtime_first_object or marker_first_object or label_filename
    if first_object_name:
        if runtime_first_object:
            field_sources["source.first_object_name"] = "runtime"
        elif marker_first_object:
            field_sources["source.first_object_name"] = "gcode_marker"
        else:
            field_sources["source.first_object_name"] = "gcode_object_label"
    runtime_plate_name = _clean(environ.get("SLIC3R_PLATE_NAME"))
    marker_plate_name = _clean(markers.get("plate_name"))
    plate_name = runtime_plate_name or marker_plate_name
    if plate_name:
        field_sources["source.plate_name"] = (
            "runtime" if runtime_plate_name else "gcode_marker"
        )
    runtime_project_name = _clean(environ.get("SLIC3R_PROJECT_NAME"))
    marker_project_name = _clean(markers.get("project_name"))
    archive_project_name = _archive_project_name(gcode)
    project_name = runtime_project_name or marker_project_name or archive_project_name
    if project_name:
        if runtime_project_name:
            field_sources["source.project_name"] = "runtime"
        elif marker_project_name:
            field_sources["source.project_name"] = "gcode_marker"
        else:
            field_sources["source.project_name"] = "project_archive"

    printer_model = sourced(
        "printer.model",
        environ.get("SLIC3R_PRINTER_MODEL"),
        config.get("printer_model"),
        "gcode_comments",
    )
    printer_preset = sourced(
        "printer.preset",
        environ.get("SLIC3R_PRINTER_SETTINGS_ID"),
        config.get("printer_settings_id"),
        "gcode_comments",
    )
    process_preset = sourced(
        "process.preset",
        environ.get("SLIC3R_PRINT_SETTINGS_ID"),
        config.get("print_settings_id"),
        "gcode_comments",
    )
    material_types = _split(environ.get("SLIC3R_FILAMENT_TYPE")) or _split(
        config.get("filament_type")
    )
    filament_presets = _split(environ.get("SLIC3R_FILAMENT_SETTINGS_ID")) or _split(
        config.get("filament_settings_id")
    )
    filaments = [
        {
            "type": material_types[index] if index < len(material_types) else None,
            "preset": filament_presets[index]
            if index < len(filament_presets)
            else None,
        }
        for index in range(max(len(material_types), len(filament_presets)))
    ]
    if filaments:
        field_sources["filaments"] = (
            "runtime"
            if environ.get("SLIC3R_FILAMENT_TYPE")
            or environ.get("SLIC3R_FILAMENT_SETTINGS_ID")
            else "gcode_comments"
        )
    if slicer_version:
        field_sources["slicer.name"] = "gcode_header"
        field_sources["slicer.version"] = "gcode_header"
    for name in stats:
        field_sources[f"print_stats.{name}"] = (
            "gcode_header" if name == "estimated_time_s" else "gcode_comments"
        )

    basename = Path(source_filename).stem if source_filename else None
    return {
        "version": 1,
        "classification": classification,
        "source": {
            "filename": source_filename,
            "basename": basename,
            "first_object_name": first_object_name,
            "object_count": object_count,
            "instance_count": instance_count,
            "plate_name": plate_name,
            "project_name": project_name,
            "object_labels": object_labels,
        },
        "slicer": {
            "name": "OrcaSlicer" if slicer_version else None,
            "version": slicer_version,
        },
        "printer": {"model": printer_model, "preset": printer_preset},
        "filaments": filaments,
        "process": {"preset": process_preset},
        "print_stats": stats,
        "field_sources": field_sources,
    }


def submission_id(gcode: Path, context: dict) -> str:
    digest = hashlib.sha256()
    with gcode.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    digest.update(json.dumps(context, sort_keys=True, separators=(",", ":")).encode())
    return digest.hexdigest()


def build_multipart(fields: dict, file_path: Path) -> tuple[bytes, str]:
    """Build a multipart/form-data body using stdlib only."""
    boundary = f"----PrintStash{uuid.uuid4().hex}"
    crlf = "\r\n"
    body = bytearray()

    for key, value in fields.items():
        if value is None:
            continue
        body += f"--{boundary}{crlf}".encode()
        body += (
            f'Content-Disposition: form-data; name="{key}"{crlf}{crlf}{value}{crlf}'
        ).encode()

    mime, _ = mimetypes.guess_type(file_path.name)
    mime = mime or "application/octet-stream"
    body += f"--{boundary}{crlf}".encode()
    body += (
        f'Content-Disposition: form-data; name="file"; filename="{file_path.name}"{crlf}'
        f"Content-Type: {mime}{crlf}{crlf}"
    ).encode()
    body += file_path.read_bytes()
    body += crlf.encode()
    body += f"--{boundary}--{crlf}".encode()

    return bytes(body), f"multipart/form-data; boundary={boundary}"


def login(
    url: str, username: str, api_key: str | None, password: str | None
) -> str | None:
    endpoint = url.rstrip("/") + "/api/v1/auth/login"
    credentials = (
        {"username": username, "api_key": api_key}
        if api_key
        else {"username": username, "password": password}
    )
    body = json.dumps(credentials).encode("utf-8")
    req = urlrequest.Request(endpoint, data=body, method="POST")
    req.add_header("Content-Type", "application/json")
    req.add_header("User-Agent", "PrintStash-OrcaHook/1.0")
    try:
        with urlrequest.urlopen(req, timeout=30) as resp:
            payload = json.loads(resp.read().decode("utf-8"))
            token = payload.get("access_token")
            if isinstance(token, str) and token:
                return token
            log.error("login response did not include access_token")
            return None
    except HTTPError as e:
        err_body = (
            e.read().decode("utf-8", errors="replace") if hasattr(e, "read") else ""
        )
        log.error("login HTTP %s: %s", e.code, err_body)
    except URLError as e:
        log.error("login network error: %s", e.reason)
    except Exception as e:  # noqa: BLE001 — defensive: never crash the slicer
        log.error("login unexpected error: %s", e)
    return None


def push(url: str, token: str, gcode: Path, fields: dict, retries: int = 3) -> bool:
    endpoint = url.rstrip("/") + "/api/v1/ingest/orca"
    body, content_type = build_multipart(fields, gcode)

    for attempt in range(1, retries + 1):
        req = urlrequest.Request(endpoint, data=body, method="POST")
        req.add_header("Content-Type", content_type)
        req.add_header("Authorization", f"Bearer {token}")
        req.add_header("User-Agent", "PrintStash-OrcaHook/1.0")
        try:
            with urlrequest.urlopen(req, timeout=30) as resp:
                payload = resp.read().decode("utf-8", errors="replace")
                log.info("upload OK [%s] %s -> %s", resp.status, gcode.name, payload)
                return True
        except HTTPError as e:
            err_body = (
                e.read().decode("utf-8", errors="replace") if hasattr(e, "read") else ""
            )
            log.error("HTTP %s on attempt %d: %s", e.code, attempt, err_body)
            if 400 <= e.code < 500:
                # Client error — won't be fixed by retry.
                return False
        except URLError as e:
            log.error("network error attempt %d: %s", attempt, e.reason)
        except Exception as e:  # noqa: BLE001 — defensive: never crash the slicer
            log.error("unexpected error attempt %d: %s", attempt, e)

        time.sleep(2**attempt)

    return False


def main() -> int:
    parser = argparse.ArgumentParser(add_help=False)
    parser.add_argument(
        "--url",
        default=os.environ.get("PRINTSTASH_URL"),
    )
    parser.add_argument(
        "--username",
        default=os.environ.get("PRINTSTASH_USERNAME"),
    )
    parser.add_argument(
        "--password",
        default=os.environ.get("PRINTSTASH_PASSWORD"),
    )
    parser.add_argument(
        "--api-key",
        default=os.environ.get("PRINTSTASH_API_KEY"),
    )
    parser.add_argument("--collection", default=None)
    parser.add_argument("--tags", default=None)
    parser.add_argument("--model-name", default=None)
    parser.add_argument("--revision-label", default=None)
    parser.add_argument("--revision-notes", default=None)
    parser.add_argument(
        "--revision-status",
        choices=("known_good", "needs_test", "failed", "archived"),
        default=None,
    )
    parser.add_argument("--recommended", action="store_true")
    parser.add_argument("--strict-mapping", action="store_true")
    parser.add_argument("--diagnostic-output", default=None)
    parser.add_argument(
        "--log-path",
        default=os.environ.get("PRINTSTASH_LOG_PATH", str(LOG_PATH)),
    )
    args, positional = parser.parse_known_args()

    try:
        configure_logging(Path(args.log_path).expanduser())
    except OSError:
        # A read-only home directory must not block slicing. stderr is normally
        # hidden by Orca, but it is still safer than raising out of the hook.
        log.handlers.clear()
        log.addHandler(logging.NullHandler())

    if not positional:
        log.error("no gcode path provided by OrcaSlicer")
        return 0  # never block export
    gcode = Path(positional[-1])
    if not gcode.exists():
        log.error("file not found: %s", gcode)
        return 0
    try:
        context = extract_native_context(gcode, os.environ)
    except Exception as error:  # noqa: BLE001 — never block the slicer
        log.error("native metadata extraction failed: %s", error)
        return 0
    if args.diagnostic_output:
        try:
            diagnostic = Path(args.diagnostic_output).expanduser()
            diagnostic.parent.mkdir(parents=True, exist_ok=True)
            diagnostic.write_text(
                json.dumps(context, indent=2, sort_keys=True) + "\n", encoding="utf-8"
            )
            log.info("wrote native metadata diagnostic to %s", diagnostic.name)
        except OSError as error:
            log.error("diagnostic write failed: %s", error)
        return 0
    if not args.url or not args.username or not (args.api_key or args.password):
        log.warning(
            "missing --url, --username, or --api-key — skipping PrintStash push"
        )
        return 0

    try:
        fields = {
            "native_context": json.dumps(
                context, sort_keys=True, separators=(",", ":")
            ),
            "submission_id": submission_id(gcode, context),
            "strict_mapping": "true" if args.strict_mapping else "false",
            "collection": args.collection,
            "tags": args.tags,
            "model_name": args.model_name,
            "revision_label": args.revision_label,
            "revision_notes": args.revision_notes,
            "revision_status": args.revision_status,
            "is_recommended": "true" if args.recommended else "false",
        }

        token = login(args.url, args.username, args.api_key, args.password)
        if not token:
            log.warning("PrintStash login failed; export still proceeds")
            return 0

        ok = push(args.url, token, gcode, fields)
        if not ok:
            log.warning("PrintStash push failed; export still proceeds")
    except Exception as error:  # noqa: BLE001 — never block the slicer
        log.error("PrintStash hook failed safely: %s", error)

    # Always exit 0 — PrintStash problems must not break slicing.
    return 0


if __name__ == "__main__":
    sys.exit(main())
